<h1>Tarefas</h1>
<br />

<table class="table table-hover">
    
    <thead>
        <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Status</th>
            <th>Responsável</th>
        </tr>
    </thead>
    
    <?php $numberOfRegisters = 0; foreach($this->tarefas as $tarefa): ?>
    <tr>
        <td><?php echo $tarefa->getTitulo(); ?></td>
        <td><?php echo $tarefa->getDescricao(); ?></td>
        <?php if($tarefa->getStatus() == True):?>
            <td>
                <span class="badge badge-pill bg-success">Concluída</span>    
            </td>
        <?php else:?>
            <td>
                <span class="badge badge-pill bg-secondary">Pendente</span>    
            </td>
        <?php endif;?>
        <td>
        <span class="badge badge-pill bg-dark"><?php echo $tarefa->getUsuario()->getNome();?></span>
        </td>
    </tr>
    <?php $numberOfRegisters += 1;?>
    <?php endforeach; ?>
    
</table>
<br />

