version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "84:80"
    volumes:
      - ./public:/www
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - php
      - db
  db:
    image: mysql:5.7
    volumes:
    - /var/lib/mysql
    container_name: mysql
    ports:
    - "3366:3366"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RoutineManager
  php:
    build: .
    container_name: php-fpm
    volumes:
    - ./public:/www