version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_5_7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RoutineManager
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dockerfiles/configs/mysql.cnf:/etc/mysql/my.cnf
    ports:
      - "3366:3306"
    networks:
      - local_network

  php:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5-6
    image: my_php_5_6
    container_name: php_5_6
    restart: always
    ports:
      - "84:80"
    volumes:
      - .:/var/www
      - ./public:/var/www/html
      - ./dockerfiles/configs/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - local_network
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local

networks:
  local_network:
    driver: bridge
