<head>
  <meta charset='utf-8' />
  <script src='https://cdn.jsdelivr.net/npm/fullcalendar@3.3.1/dist/fullcalendar.min.js'></script>
  <!-- CSS for FullCalendar -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css" rel="stylesheet" />
  <!-- JS for jQuery -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- JS for Moment.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>
  <!-- Bootstrap 5 CSS and JS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
      var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth'
      });
      calendar.render();
    });
  </script>
</head>

<body>
  <!-- Start Modal -->
  <div class="modal fade" id="event_entry_modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalLabel">Adicionar nova tarefa</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="img-container">
            <div class="row mb-3">
              <div class="col-sm-12">
                <div class="form-group">
                  <label for="tarefa-titulo">Título da tarefa</label>
                  <input type="text" name="tarefa-titulo" id="tarefa-titulo" class="form-control" placeholder="Digite o nome da tarefa">
                </div>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-sm-12">
                <div class="form-group">
                  <label for="tarefa-descricao">Descrição</label>
                  <textarea class="form-control" name="tarefa-descricao" id="tarefa-descricao" rows="3" placeholder="Descrição da tarefa"></textarea>
                </div>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="tarefa-inicio">Início da tarefa</label>
                  <input type="date" name="tarefa-inicio" id="tarefa-inicio" class="form-control" placeholder="Data de início da tarefa">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="tarefa-fim">Fim da tarefa</label>
                  <input type="date" name="tarefa-fim" id="tarefa-fim" class="form-control" placeholder="Data do fim da tarefa">
                </div>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-sm-12">
                <label for="tarefa-usuario_id">Usuário Responsável</label>
                <select id="tarefa-usuario_id" class="form-select" name="tarefa-usuario_id">
                  <?php foreach ($users as $id => $usuario): ?>
                    <option value="<?= $id ?>"><?= $usuario ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </div>
            <input type="hidden" name="tarefa-status" id="tarefa-status" value="0">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" onclick="salvarTarefa()">Salvar Tarefa</button>
        </div>
      </div>
    </div>
  </div>
  <!-- End Modal -->
  <div id='calendar'></div>
</body>
<script>
  $(document).ready(function() {
    var events = <?php echo $this->eventsJson; ?>;


    $('#calendar').fullCalendar({
      defaultView: 'month',
      timeZone: 'local',
      editable: false,
      selectable: true,
      selectHelper: true,
      select: function(start, end) {
        $('#tarefa-inicio').val(moment(start).format('YYYY-MM-DD'));
        $('#tarefa-fim').val(moment(end).format('YYYY-MM-DD'));
        $('#event_entry_modal').modal('show');
      },
      events: events,
      eventRender: function(event, element, view) {
        element.find('.fc-title').text(event.title + ' | | ' + event.responsavel  + ' | | ' + (event.status ? 'Concluída' : 'Pendente'));
        
        if (event.status === true) {
          element.css('background-color', 'green');
          element.css('border-color', 'green');
        } else if (event.status === false) {
          element.css('background-color', 'gray');
          element.css('border-color', 'gray');
        }
      }
    });
  });
  
  function salvarTarefa() {
    console.log($("#tarefa-titulo").val());
    var titulo = $("#tarefa-titulo").val();
    var usuario_id = $("#tarefa-usuario_id").val();
    var descricao = $("#tarefa-descricao").val();
    var dataHoraInicio = $("#tarefa-inicio").val();
    var dataHoraFim = $("#tarefa-fim").val();
    var status = $("#tarefa-status").val();
    $('#event_entry_modal').modal('hide');
    if (titulo == "" || dataHoraInicio == "" || dataHoraFim == "" || usuario_id =="" || descricao=="" || status=="") {
      alert("Por favor, preencha todos os campos.");
      return false;
    }
    $.ajax({
      url: "calendario",
      type: "POST",
      dataType: 'json',
      data: JSON.stringify({
        titulo: titulo,
        usuario_id: usuario_id,
        descricao: descricao,
        dataHoraInicio: dataHoraInicio,
        dataHoraFim: dataHoraFim,
        status: status
      }),
      success: function(response) {
        $('#event_entry_modal').modal('hide');
        if (response.status == true) {
          alert(response.msg);
          location.reload();
        } else {
          alert(response.msg);
        }
      },
      error: function(xhr, status, error) {
        //console.log('AJAX Error:', xhr.status, status, error);
        location.reload();
      }
    });
    return false;
  }
</script>

</html>