<div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card shadow-lg" style="width: 100%; max-width: 600px;">
            <h3 class="text-center mt-3">Editar Tarefa</h3>
            <div class="card-body">
                <?php
                $form = $this->form; 

                $form->setAttribute('action', $this->url('routinemanager-admin', array('controller'=>'tarefas', 'action'=>'edit')));

                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formHidden($form->get('id')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('titulo')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('descricao')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('status')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('dataHoraInicio')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('dataHoraFim')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('usuario_id')); ?>
                </div>
                
                <div class="d-grid">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
                
                <?php
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
