<h3>Nova Tarefa</h3>

<br/>

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('routinemanager-admin',array('controller'=>'tarefas','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('titulo'));
echo $this->formRow($form->get('descricao'));
echo $this->formRow($form->get('status'));
echo $this->formRow($form->get('usuarioId'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>