<?php echo $this->doctype(); ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Mateusfln - Routine Manager')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css')
        ->prependStylesheet("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css")

    ?>

    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
    ?>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?php echo $this->url('routinemanager-admin', array('controller' => 'tarefas')) ?>">RoutineManager Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('routinemanager-admin', array('controller' => 'usuarios')) ?>">Usuários</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('routinemanager-admin', array('controller' => 'tarefas')) ?>">Tarefas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('routinemanager-admin', array('controller' => 'tarefas', 'action' => 'calendario')) ?>">Calendário</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('routinemanager-admin-auth') ?>"><i class="bi bi-person-circle"></i> Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->url('routinemanager-admin-logout') ?>"><i class="bi bi-box-arrow-right"></i> Log Out</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <div class="container">
        <?php echo $this->content; ?>
        <hr>
        <footer>
            <p>by Mateusfln :D</p>
        </footer>
    </div>
    <?php echo $this->inlineScript() ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>