<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Mateusfln - Routine Manager')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css')
        ?>

<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('routinemanager-home') ?>">Routine Manager</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                    <?php //if ($this->UserIdentity('RoutineManagerAdmin')): ?>
                                <li class="active"><a href="<?php echo $this->url('routinemanager-admin', array('controller' => 'tarefas')) ?>">Tarefas</a></li>
                                <li class="active"><a href="<?php echo $this->url('routinemanager-admin', array('controller' => 'usuarios')) ?>">Usuários</a></li>
                                <li class="active"><a href="<?php echo $this->url('routinemanager-admin-logout') ?>">Logout</a></li>
                                
                    <?php //endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>by Mateusfln :D</p>
            </footer>
        </div>
<?php echo $this->inlineScript() ?>
    </body>
</html>
