<h3>Editar Usuário</h3>

<br/>

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('routinemanager-admin-interna',array('controller'=>'usuarios','action'=>'edit')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password')).PHP_EOL;
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

