<h1>Usuários</h1>
<br />

<p>
    <a class="btn btn-outline-success" href="<?php echo $this->url('routinemanager-admin', array('controller' => 'usuarios', 'action' => 'new')); ?>">
        <i class="bi bi-plus-square"></i> Novo
    </a>
</p>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col" class="text-end">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php $numberOfRegisters = 0;
            foreach ($this->data as $usuario): ?>
                <tr>
                    <td><?php echo $usuario->getId(); ?></td>
                    <td><?php echo $usuario->getNome(); ?></td>
                    <td><?php echo $usuario->getEmail(); ?></td>
                    <td class="text-end">
                        <a class="btn btn-outline-info btn-sm" href="<?php echo $this->url('routinemanager-admin-interna', array('controller' => 'usuarios', 'action' => 'edit', 'id' => $usuario->getId())); ?>">
                            <i class="bi bi-pencil-square"></i> Editar
                        </a>
                        <a class="btn btn-outline-danger btn-sm" href="<?php echo $this->url('routinemanager-admin-interna', array('controller' => 'usuarios', 'action' => 'delete', 'id' => $usuario->getId())); ?>">
                            <i class="bi bi-trash3"></i> Deletar
                        </a>
                    </td>
                </tr>
                <?php $numberOfRegisters += 1; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<br />

<?php
if ($this->data->getDefaultItemCountPerPage() <= $numberOfRegisters || $this->data->getCurrentPageNumber() != 1) {
    echo $this->paginationControl($this->data, 'Sliding', 'paginator');
}
?>