<h1>Usuários</h1>
<br />

<p>
    <a class="btn btn-outline-success " href="<?php echo $this->url('routinemanager-admin',array('controller'=>'usuarios','action'=>'new')); ?>">
    <i class="bi bi-plus-square"></i>
        Novo
    </a>
</p>

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Ação</th>
        </tr>
    <thead>
    
    <?php foreach($this->data as $usuario): ?>
    <tr>
        <td><?php echo $usuario->getId(); ?></td>
        <td><?php echo $usuario->getNome(); ?></td>
        <td><?php echo $usuario->getEmail(); ?></td>
        <td>
            <a  class="btn btn-outline-info" href="<?php echo $this->url('routinemanager-admin',
                    array('controller'=>'usuarios','action'=>'edit','id'=>$usuario->getId())); ?>"><i class="bi bi-pencil-square"></i>Editar</a>
            <a  class="btn btn-outline-danger" href="<?php echo $this->url('routinemanager-admin',
                    array('controller'=>'usuarios','action'=>'delete','id'=>$usuario->getId())); ?>"><i class="bi bi-trash3"></i>Deletar</a>
        </td>
    </tr>
    <?php endforeach; ?>
    
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>