    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card shadow-lg" style="width: 100%; max-width: 600px;">
        <h3 class="d-flex justify-content-center align-items-center mt-3">Novo Usuário</h3>
            <div class="card-body">
                <?php
                $form = $this->form; 

                $form->setAttribute('action', $this->url('routinemanager-admin',array('controller'=>'usuarios','action'=>'new')));

                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formHidden($form->get('id')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('nome')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('email')); ?>
                </div>
                
                <div class="d-grid mb-3">
                    <?php echo $this->formRow($form->get('password')); ?>
                </div>
                
                <div class="d-grid">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
                
                <?php
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
