<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . "/page/" . $page;
    else
        return preg_replace('/\d/', $page, $urlPattern);
};
?>

<div class="container pb-4">
    <?php if ($this->pageCount): ?>
        <div class="d-flex flex-column align-items-center">
            <div class="mb-3">
                <span class="text-muted">
                    <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> páginas
                </span>
            </div>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <!-- First page link -->
                    <?php if (isset($this->previous)): ?>
                        <li class="page-item">
                            <a class="page-link" href="<?php echo $formatUrl(1); ?>" aria-label="Primeira">
                                <span aria-hidden="true">&laquo;&laquo;</span> Primeira
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="<?php echo $formatUrl($this->previous); ?>" aria-label="Anterior">
                                <span aria-hidden="true">&laquo;</span> Anterior
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="page-item disabled">
                            <span class="page-link" aria-label="Primeira">
                                <span aria-hidden="true">&laquo;&laquo;</span> Primeira
                            </span>
                        </li>
                        <li class="page-item disabled">
                            <span class="page-link" aria-label="Anterior">
                                <span aria-hidden="true">&laquo;</span> Anterior
                            </span>
                        </li>
                    <?php endif; ?>

                    <!-- Next page link -->
                    <?php if (isset($this->next)): ?>
                        <li class="page-item">
                            <a class="page-link" href="<?php echo $formatUrl($this->next); ?>" aria-label="Próximo">
                                Próximo <span aria-hidden="true">&rsaquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="<?php echo $formatUrl($this->pageCount); ?>" aria-label="Último">
                                Último <span aria-hidden="true">&rsaquo;&rsaquo;</span>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="page-item disabled">
                            <span class="page-link" aria-label="Próximo">
                                Próximo <span aria-hidden="true">&rsaquo;</span>
                            </span>
                        </li>
                        <li class="page-item disabled">
                            <span class="page-link" aria-label="Último">
                                Último <span aria-hidden="true">&rsaquo;&rsaquo;</span>
                            </span>
                        </li>
                    <?php endif; ?>
                </ul>
            </nav>
        </div>
    <?php endif; ?>
</div>
